### ISSUE TITLE
Other romance mod 

### ISSUE THREAD

**Issue by cambridge100** [littlefiredragon/WOTR_WoljifRomanceMod#1]
Since there is no possibility to send a private message, i use this form of issue to make a question - i hope i use this form of issue Correctly, because i'm newbie on this site and understand it's mechanics not to good.

Greetings, friend from other side of planet! I'm russian fan of pathfinder games and also fan of Jaethal and Camelia alike 

My knowledge of English grammatics is kind of poor, so i can make mistakes, but i'm sure, i can speak in more or less understandable way 

It's really awesome, that we have this glorious woman to be romanced - Camelia, but Jaethal never were as a romance option - and that's a problem

I wrote to Owlcat studio and they don't have a plans to create a romance with Jaethal, so, i guess... If this roman will exist, he will exist only by handiwork of Fans

So... Do you interested in creating romance with Jaethal? Or maybe you know about people (forums), who interested in making mod romance with Jaethal?

As for me, i'm not engineer, nor designer or whoever else - just an ordinary guy, but i can (and want) to involve my own Money to create Romance mod with Jaethal - to bring this project to life

**Comment by littlefiredragon** [comment]
Hello! The "Issues" section is for reporting bugs. You can send me a PM on NexusMods or @ me on the Pathfinder discord channel.
Unfortunately, I can't help you. Kingmaker and Wrath of the Righteous do not work the same way. This framework will not work for Kingmaker without many changes, so it can't be used for a Jaethal romance. I do not know anything about modding Kingmaker, and I do not have any plans to make mods for it.
