### ISSUE TITLE
CompanionInParty Condition bug

### ISSUE THREAD

**Issue by Meow-fried** [littlefiredragon/WOTR_WoljifRomanceMod#2]
Hi Paladingineer,

I'm using your tools to write a story mod. First of all, thank you for making modding the story easy!

There seems to be a bug with regard to the CompanionInParty Condition, causing it always returns `false.`
This affects CreateCompanionAvailableCondition, CreateCompanionDeadCondition, and CreateCompanionInPartyCondition in ConditionalTools.cs. Can't figure out why.

For example, if I create a test dialogue branch using
```
var a_TestSeelah = DialogTools.CreateAnswer("TEST_a_companion");
var c_SeelahYes = DialogTools.CreateCue("TEST_c_companionconditiongood"); 
var c_SeelahNo = DialogTools.CreateCue("TEST_c_companionconditionfail");
DialogTools.AnswerAddNextCue(a_TestSeelah, c_SeelahYes);
DialogTools.AnswerAddNextCue(a_TestSeelah, c_SeelahNo);
DialogTools.CueAddCondition(c_SeelahYes, ConditionalTools.CreateCompanionAvailableCondition("", Companions.Seelah));
```
it will always go to the No cue (Seelah is of course in my party). 

If I hard copy an existing condition from an Owlcat-wrote cue, such as the one (guid: 5c58dadbf6eb78144bf84dbdebf2f4bb) below,
![Screenshot 2022-04-12 205521](https://user-images.githubusercontent.com/100874063/163034245-03d84707-57dc-4f89-9666-b770c9bcc84d.png)
the testing dialog will go to the Yes cue, which puzzles me since the conditions should be the same to my eyes.

**Comment by littlefiredragon** [comment]
Hm. Can you try making this change to your local copy of the CueAddCondition function?
Between lines 279 and 280, add:
`condition.Owner = cue;`
Let me know if that fixes it. If so, I'll have a few fixes to make to certain functions.

**Comment by Meow-fried** [comment]
Yep. Adding Owner fixes it.
Weird that it only seems to affect CompanionInParty, though. Is it because CompanionInParty references a BlueprintUnit so it must have an Owner?

Anyway, thanks!

**Comment by littlefiredragon** [comment]
I will fix it immediately. The owner is added during assignment of a condition to a blueprint, not during creation of the condition... and I happened to miss the owner assignment in AddConditionToCue.
As for why a given condition requires an owner and a different one doesn't... no clue. I'll go through and make sure owner assignments are properly placed in all relevant functions.
