### ISSUE TITLE
Can't load game with mod installed as of patch 2.3.0bb

### ISSUE THREAD

**Issue by OrienasWizard** [littlefiredragon/WOTR_WoljifRomanceMod#5]
When loading the game, if the mod is installed, the progress bar gets stuck at around 30%. If the mod is uninstalled, the game is able to load into the main menu, but then any save game that used this mod cannot be loaded, making the game unplayable.

**Comment by littlefiredragon** [comment]
Fixed in 1.1.4. Thanks for the report! I wasn't getting notified of people posting on nexusmods so this was the only way I knew the mod was broken!
